version: 0.0
os: linux
files:
  - source: /webapp.war
    destination: /opt/tomcat/webapps/

hooks:
  ApplicationStop:
    - location: script/stop.sh

  AfterInstall:
    - location: script/start.sh
      timeout: 300
      runas  : root


