version: 0.0
os: linux
files:
  - source: /webapp.war
    destination: /opt/tomcat/webapps/

hooks:
  ApplicationStop:
    - location: script/stop.sh
  BeforeInstall:
    - location: script/status.sh
      timeout: 300
  AfterInstall:
    - location: script/start.sh
      timeout: 300


